<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No auto-budgetSet a fixed amount eve_005aeb</name>
   <tag></tag>
   <elementGuidId>1fed7b40-4a78-4857-a01f-cdd7f8de8ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>286f158e-b343-43d9-ac63-7355a0c8363e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>11ccb2a7-a8a6-4ef1-9ba8-dc04647e5017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_type</value>
      <webElementGuid>cfe848ff-82e0-4fa6-a7ce-9e1126abeeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_type</value>
      <webElementGuid>aa7f216b-241e-4fa8-b1ac-c9d6b2f9d70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b74e1105-5e85-474d-9afc-8daee291d8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cacda328-5472-451c-a06b-3ba62da4b020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending</value>
      <webElementGuid>79cd74b4-6eda-42b6-a11d-0c5839d7ae04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_type&quot;)</value>
      <webElementGuid>5a41162f-3ec4-4c85-b44f-94404d2f9a5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_type']</value>
      <webElementGuid>a932dbb8-a13e-4eb2-a74f-d340bf847398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_type_holder']/div/select</value>
      <webElementGuid>af163934-f996-43b1-b319-57f29555ca4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>be5d3fe3-5e7d-46f9-84a8-c8212eeab2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_type' and @id = 'ffInput_auto_budget_type' and (text() = 'No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending' or . = 'No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending')]</value>
      <webElementGuid>4190580d-7edd-40c1-b7d5-ef6d2e5ef833</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
