<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DailyWeeklyMonthlyQuarterlyEvery hal_69941c</name>
   <tag></tag>
   <elementGuidId>26ab803d-3741-48eb-8ea8-8fe67881eaf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1f4d75ae-ac25-4768-9fb4-e4413b3766de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e290d226-57f7-4657-8c97-26c0b2c020fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_period</value>
      <webElementGuid>301e7a8a-d81e-462c-9f25-f0568966753b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_period</value>
      <webElementGuid>1b0c1804-fae4-456f-baab-8a763dacf718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0937469c-d734-4bf8-be3e-1dbed2d926ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75f4fa75-dcd6-4a6d-9f80-4d009d04398f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DailyWeeklyMonthlyQuarterlyEvery half yearYearly</value>
      <webElementGuid>f401cfc4-e4a0-4799-bb31-26defc54e1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_period&quot;)</value>
      <webElementGuid>2082aeb1-dc02-4ddc-999f-b0c38f878273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_period']</value>
      <webElementGuid>4008c93c-d755-4e4f-a4e7-603a1ec580c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_period_holder']/div/select</value>
      <webElementGuid>8ce4afff-3c96-449e-a210-ef1a40a96e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>bcd85bc6-0d22-43dd-9dbe-8e570017b232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_period' and @id = 'ffInput_auto_budget_period' and (text() = 'DailyWeeklyMonthlyQuarterlyEvery half yearYearly' or . = 'DailyWeeklyMonthlyQuarterlyEvery half yearYearly')]</value>
      <webElementGuid>03e3bb91-2691-4142-bb20-40f2a7ba84c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
